/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeNumberTemplate;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PrimeNumberTest {
    @Test
    void TestIsPrimeA(){
        assertTrue(PrimeNumber.isPrime(7));
    }
    @Test
    void TestIsPrimeB(){
        assertFalse(PrimeNumber.isPrime(4));
    }
    @Test
    void TestIsPrimeC(){
        try{
            PrimeNumber.isPrime(-1);
        }
        catch (Exception e){
            assertTrue(e.getMessage().equals("Parameter 'num' cannot be less than 0"));
        }
    }
}
