/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeNumberTemplate;

public class PrimeNumber {
    public static void main(String[] args){
        //ToDo: Print statement that tells you if the umber is prime or not
    }

    public static boolean isPrime(int num){
        /**
         *  ToDo: return T/F if val is prime or
         *  not and create error message if the number is less
         *  than 0
         */
    }
}