/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeNumberTemplate;

import humanize.Humanize;

public class PrimeNumber {
    public static void main(String[] args){
       //ToDo
    }

    public static boolean isPrime(int num){
        //ToDo
    }
}